apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-test-deployment
  namespace: monitoring
  labels:
    app: java-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-test
  template:
    metadata:
      labels:
        app: java-test
    spec:
      containers:
      - name: java-test
        image: java-jmx-in-docker-sample-app_loop:3.0
        ports:
        - containerPort: 9010
        - containerPort: 5005
        - containerPort: 8080
