apiVersion: v1
kind: Service
metadata:
  name: java-test-service
  namespace: monitoring
  labels:
    name: java-test-service
spec:
  selector:
    app: java-test
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
